GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "the viral bearer",
    "author": "virathol",
    "url": "url",
    "likes": 100
}